Compress the zipfile as much as possible
icon-project/icon-sdk-python pull request #60
Opened 2021-01-15 00:36 UTC by Spl3en

For big contracts, the 2,500,000,000 step limit may be reached because the zipfile isn't compressed well enough

`compresslevel` parameter has been added since python 3.7

https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile

2021-01-15 02:31 UTC, sink772 requested changes
Thanks for taking your time to improve the code. Please see my comment inline.

2021-01-15 02:31 UTC, sink772 commented on iconsdk/libs/in_memory_zip.py
> +                zf = ZipFile(_path, 'r', ZIP_DEFLATED, False, compresslevel=9)
This block is just for reading a existing zip file and writing its content into memory. Thus we don't need to specify `compresslevel` here.

2021-01-15 02:51 UTC, Spl3en commented
Good catch, thanks !

2021-01-17 08:47 UTC, sink772 approved these changes

2021-01-17 08:49 UTC, merged